version: '{build}'
build: off

skip_commits:
  message: /\[ci\s+skip\]/

environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '8'

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test

matrix:
  fast_finish: true

cache:
  - node_modules
