name: $(BuildID)

resources:
  repositories:
    - repository: apt
      type: github
      name: futagoza/apt
      endpoint: futagoza

variables:
- group: 'env-variables'

jobs:

- template: eslint.yml@apt

- template: node-test.yml@apt
  parameters:
    afterEach:
    - script: yarn coverage
      displayName: 'mocha > codecov.io'
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)
