name: ci

on: [ push, pull_request ]

jobs:

  preflight:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "Will run CI on commit ${{ github.event.head_commit.message }}"

  Lint:
    needs: preflight

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: Install dependencies
      run: npx yarn --ignore-engines

    - name: Lint JavaScript files using ESLint
      run: npm run lint

  Test:
    needs: preflight

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 10.x, 12.x ]

    steps:
    - uses: actions/checkout@master

    - name: Install Node.js
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npx yarn --ignore-engines

    - name: Run tests
      run: npm run test

    - name: Publish code coverage results
      run: npm run coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
